name: Rust
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INPUT_2023_01: ${{ secrets.INPUT_2023_01 }}
      INPUT_2023_01_1_EXAMPLE: ${{ secrets.INPUT_2023_01_1_EXAMPLE }}
      INPUT_2023_01_2_EXAMPLE: ${{ secrets.INPUT_2023_01_2_EXAMPLE }}
      INPUT_2023_02: ${{ secrets.INPUT_2023_02 }}
      INPUT_2023_02_EXAMPLE: ${{ secrets.INPUT_2023_02_EXAMPLE }}
      INPUT_2023_03: ${{ secrets.INPUT_2023_03 }}
      INPUT_2023_03_EXAMPLE: ${{ secrets.INPUT_2023_03_EXAMPLE }}
      RESPONSE_2023_01_1_EXAMPLE: ${{ secrets.RESPONSE_2023_01_1_EXAMPLE }}
      RESPONSE_2023_01_2_EXAMPLE: ${{ secrets.RESPONSE_2023_01_2_EXAMPLE }}
      RESPONSE_2023_02_1_EXAMPLE: ${{ secrets.RESPONSE_2023_02_1_EXAMPLE }}
      RESPONSE_2023_02_2_EXAMPLE: ${{ secrets.RESPONSE_2023_02_2_EXAMPLE }}
      RESPONSE_2023_03_EXAMPLE: ${{ secrets.RESPONSE_2023_03_EXAMPLE }}
    steps:
    - uses: actions/checkout@v3
    - name: Check style
      run: cargo fmt --all -- --check
    - name: Check with `cargo check`
      run: cargo check --all
    - name: Check with Clippy
      run: cargo clippy --all -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Prepare tests
      run: sh utils/prepare_inputs_and_responses.sh
    - name: Run tests
      run: cargo test --verbose
